# Process indexes

This notebook calculates key Economic Complexity indicators: RCA, M matrix, ECI, PCI, and opportunity metrics such as proximity, density, and strategic value. These are used to evaluate the productive structure of states and identify diversification paths.

In [2]:
import pandas as pd
import numpy as np

## 1. Read data

Read the necessary files and select which data and aggregation you want to use

In [3]:
# Select which data and aggregation to use

data_choice = "labor" # trade / labor
labor_aggregation = "metropolitan_area" # state / metropolitan_area

In [ ]:
# Directory structure and read database

if data_choice == "trade":
    DATASETS_DIR = './datasets_trade/'
    OUTPUTS_DIR = "./outputs_trade/"
    variable = "trade_value"
    code = "HS6"
    location = 'location'
    
    # Read the database created in create_trade_database.ipynb
    data = pd.read_parquet(DATASETS_DIR + "df_trade_complete.parquet",engine='fastparquet')
    data = data.loc[data.location != "USA"] # Since we are adding the US states, we should remove the country to avoid duplication 
    data = data.groupby(['location', 'HS6'], as_index=False)['trade_value'].sum() # Group by location and HS6, summing the trade value
    df_temp = data.groupby(["location"]).sum() # We are adding some quality restrictions: we'll delete all countries with less than $1b trade
    remove_countries = df_temp.loc[df_temp["trade_value"]<1000000000].index 
    data = data.loc[~data.location.isin(remove_countries)]
    data = data.loc[data[variable]>0]
    print(data.shape)
    print(data.head())

elif data_choice == "labor":
    if labor_aggregation == "state":
        DATASETS_DIR = './datasets_labor_states/'
        OUTPUTS_DIR = "./outputs_labor_states/"
        variable = "EMP"
        location = "STATE_NAME"
        code = "NAICS2017"

        data= pd.read_parquet(DATASETS_DIR + "df_labor_usa_states.parquet",engine='fastparquet')
        data['NAICS2017'] = data['NAICS2017'].astype(str) # Ensure NAICS is string*
        data['naics_level'] = data['NAICS2017'].str.len() # Add a column for NAICS code length
        data = data[data.naics_level == 5]
        df_temp = data.groupby([location]).sum() 
        remove_states = df_temp.loc[df_temp[variable]<100000].index 
        data = data.loc[~data[location].isin(remove_states)]
        data = data.loc[~data[location].isin(["Puerto Rico"])]
        data = data.loc[data[variable]>0]
        print(data.shape)
        print(data.head())
        
    elif labor_aggregation == "metropolitan_area":
        DATASETS_DIR = './datasets_labor_metropolitan_area/'
        OUTPUTS_DIR = "./outputs_labor_metropolitan_area/"
        variable = "EMP"
        location = "metropolitan statistical area/micropolitan statistical area"
        code = "NAICS2017"

        data_2022= pd.read_parquet(DATASETS_DIR + "df_labor_usa_metropolitan_area.parquet",engine='fastparquet')
        data_2022['NAICS2017'] = data_2022['NAICS2017'].astype(str) # Ensure NAICS is string*
        data_2022['naics_level'] = data_2022['NAICS2017'].str.len() # Add a column for NAICS code length
        mask_5digit = data_2022["NAICS2017"].str.len().eq(6) & data_2022["NAICS2017"].str.isnumeric()
        data_2022 = data_2022[mask_5digit]

        data_2023= pd.read_parquet(DATASETS_DIR + "df_labor_usa_metropolitan_area_2023.parquet",engine='fastparquet')
        data_2023['NAICS2017'] = data_2023['NAICS2017'].astype(str) # Ensure NAICS is string*
        data_2023['naics_level'] = data_2023['NAICS2017'].str.len() # Add a column for NAICS code length
        mask_5digit = data_2023["NAICS2017"].str.len().eq(6) & data_2023["NAICS2017"].str.isnumeric()
        data_2023 = data_2023[mask_5digit]

        
        print(data_2023.shape)
        print(data_2023.head())

(204024, 5)
   NAICS2017  EMP STATE  \
5     115112   19  None
10    212321   15  None
15    221122   86  None
20    236115   28  None
21    236118   55  None

   metropolitan statistical area/micropolitan statistical area  naics_level
5                                               10100                     6
10                                              10100                     6
15                                              10100                     6
20                                              10100                     6
21                                              10100                     6

In [7]:
data = pd.concat([data_2023, data_2022], ignore_index=True)

data = (data.assign(NAICS2017=lambda d: d["NAICS2017"].astype(str))
          .loc[lambda d: d["NAICS2017"].str.len().eq(6) & d["NAICS2017"].str.isnumeric()]
          .groupby(["metropolitan statistical area/micropolitan statistical area", "NAICS2017"], as_index=False).agg(EMP=("EMP","mean")))
data["EMP"] = data["EMP"].round().astype(int)
data.head()

  metropolitan statistical area/micropolitan statistical area NAICS2017  EMP
0                                              10100             115112   14
1                                              10100             212321   17
2                                              10100             221122   87
3                                              10100             236115   28
4                                              10100             236118   54

In [21]:
data.loc[data["NAICS2017"]== "332993"]

,metropolitan statistical area/micropolitan statistical area,NAICS2017,EMP
148653,38060,332993,251
203918,47900,332993,66

In [8]:
data.loc[data.NAICS2017 == "31-33"]

Empty DataFrame
Columns: [metropolitan statistical area/micropolitan statistical area, NAICS2017, EMP]
Index: []

## 1. Calculate RCA (Revealed Comparative Advantage)

Compute the RCA matrix to determine whether each region (state or country) is competitively exporting a product.

In [9]:
df_base = data[[location, code, variable]].copy()
df_base.head()

  metropolitan statistical area/micropolitan statistical area NAICS2017  EMP
0                                              10100             115112   14
1                                              10100             212321   17
2                                              10100             221122   87
3                                              10100             236115   28
4                                              10100             236118   54

In [10]:
# Calculate the vector of export by location/country (sum c Xcp)

df_agrup_c = df_base.groupby([location])[[variable]].sum()
df_agrup_c.head()

                                                      EMP
metropolitan statistical area/micropolitan stat...
10100                                               12545
10140                                               12011
10180                                               57055
10220                                                7150
10300                                               16715

In [11]:
# Calculate the ratio of the export of a product in all the country's exports.

df_prov = df_base.merge(df_agrup_c, how='left', on=location)
df_prov['porc_country']=df_prov[f'{variable}_x']/df_prov[f'{variable}_y' ]
df_prov.head()

,metropolitan statistical area/micropolitan statistical area,NAICS2017,EMP_x,EMP_y,porc_country
0,10100,115112,14,12545,0.001116
1,10100,212321,17,12545,0.001355
2,10100,221122,87,12545,0.006935
3,10100,236115,28,12545,0.002232
4,10100,236118,54,12545,0.004305

In [12]:
#Calculate the vector of export by product (sum c Xcp)

df_agrup_p = df_base.groupby([code])[[variable]].sum()
df_agrup_p.head()

             EMP
NAICS2017
113110      1000
113210       276
113310     25539
114111      2047
114112       803

In [13]:
# Calculate total export

df_agrup_pc = df_agrup_p[variable].sum()
df_agrup_pc

119504604

In [14]:
# Calculate the ratio of an exported product over total export

df_agrup_p[f'{variable}_total'] = df_agrup_pc
df_agrup_p['porc_product'] = df_agrup_p[variable]/df_agrup_p[f'{variable}_total']
df_agrup_p.head()

             EMP  EMP_total  porc_product
NAICS2017
113110      1000  119504604      0.000008
113210       276  119504604      0.000002
113310     25539  119504604      0.000214
114111      2047  119504604      0.000017
114112       803  119504604      0.000007

In [15]:
# Unify both tables and ratios to calculate RCA.

df_RCA = df_prov.merge(df_agrup_p, how='left', on=code)

df_RCA['RCA'] = df_RCA['porc_country'] / df_RCA['porc_product']
df_RCA['M'] = np.where(df_RCA['RCA'] >= 1, 1, 0)

df_RCA.drop(columns=[variable, f'{variable}_total', f'{variable}_y'],inplace=True)
df_RCA.rename(columns={f'{variable}_x': variable}, inplace=True)
    
df_RCA.head()

,metropolitan statistical area/micropolitan statistical area,NAICS2017,EMP,porc_country,porc_product,RCA,M
0,10100,115112,14,0.001116,0.000071,15.730720,1
1,10100,212321,17,0.001355,0.000145,9.336596,1
2,10100,221122,87,0.006935,0.002583,2.684870,1
3,10100,236115,28,0.002232,0.001834,1.217123,1
4,10100,236118,54,0.004305,0.003813,1.129029,1

In [16]:
# rca by country
df_RCA.groupby(location)[['M']].sum().sort_values(by='M', ascending=False)

                                                      M
metropolitan statistical area/micropolitan stat...
31080                                               436
16980                                               425
19100                                               380
38900                                               370
40140                                               355
...                                                 ...
22340                                                30
45020                                                30
39700                                                14
49820                                                11
31060                                                10

[925 rows x 1 columns]

In [17]:
# Transform matrix to numpy
locations = df_RCA[location].unique()
products = df_RCA[code].unique()

df_RCA['loc_int'] = df_RCA[location].apply(lambda x: np.where(locations == x)[0][0])
df_RCA['prod_int'] = df_RCA[code].apply(lambda x: np.where(products == x)[0][0])
df_RCA.head()

,metropolitan statistical area/micropolitan statistical area,NAICS2017,EMP,porc_country,porc_product,RCA,M,loc_int,prod_int
0,10100,115112,14,0.001116,0.000071,15.730720,1,0,0
1,10100,212321,17,0.001355,0.000145,9.336596,1,0,1
2,10100,221122,87,0.006935,0.002583,2.684870,1,0,2
3,10100,236115,28,0.002232,0.001834,1.217123,1,0,3
4,10100,236118,54,0.004305,0.003813,1.129029,1,0,4

In [18]:
len(locations), len(products)

(925, 964)

## 2. Calculate M matrix

Binary matrix indicating whether a region is competitive (RCA > 1) in each product.

In [19]:
# Create a matrix of zeros and fill
Mpa = np.zeros((df_RCA[location].nunique(), df_RCA[code].nunique()),
               dtype=np.int64)

for row in df_RCA.loc[df_RCA.M == 1].iterrows():
    Mpa[row[1].loc_int, row[1].prod_int] = 1

In [20]:
print('Cuantos elementos tienen RCA > 1 segun df_RCA:', len(df_RCA.loc[df_RCA.M == 1]))
print('Cuantos elementos tienen RCA > 1 segun Mpa:   ', Mpa.sum())

Cuantos elementos tienen RCA > 1 segun df_RCA: 113835
Cuantos elementos tienen RCA > 1 segun Mpa:    113835

### 2.1 Calculate Diversity

Sum across products for each region to get diversity: how many products a region exports competitively.

In [22]:
diversity = Mpa.sum(axis = 1)
diversity.shape

(925,)

### 2.2 Calculate Ubiquity

Sum across regions for each product to get ubiquity: how many regions are competitive in each product.

In [23]:
ubiquity = Mpa.sum(axis = 0)
ubiquity.shape

(964,)

### 2.3 Calculate Inverse Matrix

Create the inverse normalized matrix used in ECI and PCI calculations.

In [24]:
D_inv = np.diag(1/diversity)
D_inv.shape

(925, 925)

In [25]:
U_inv = np.diag(1/ubiquity)
U_inv.shape

(964, 964)

## 3. Calculate $\tilde{M}$ matrix
Double-standardized matrix used to compute eigenvectors for complexity metrics.

In [26]:
temp_Mpa_1 = Mpa.copy().astype(float)
for i in range(len(products)):
    temp_Mpa_1[:, i] = temp_Mpa_1[:, i]/ubiquity[i]

In [27]:
temp_Mpa_1.dtype, temp_Mpa_1.shape
Sccprima = np.matmul(temp_Mpa_1, Mpa.transpose())
Sccprima.shape

(925, 925)

In [28]:
Mmonio_c = np.matmul(D_inv, Sccprima)
Mmonio_c.shape

(925, 925)

## 4. Calculate ECI and PCI

Use the eigenvectors of the standardized matrix to calculate Economic Complexity Index (ECI) and Product Complexity Index (PCI).

In [29]:
def calc_complexity(mmonio):
    autovalores, autovectores = np.linalg.eig(mmonio)
    second_idx = np.where(autovalores == -np.sort(-autovalores)[1])[0][0]
    
    # second eigenvalue is the variance: the ECI
    complexity = autovectores[:, second_idx].real
    return complexity

In [31]:
# Check that the ECIs are not reversed. If they are reversed, run next cell to change their sign. This is because the eigenvector calculation has an indeterminate direction and must be determined manually.
eci_raw = calc_complexity(Mmonio_c)
eci_norm = (eci_raw - eci_raw.mean())/eci_raw.std()
eci_norm = -eci_norm

# ECI results by country
df_eci = pd.DataFrame({'location': locations, 'ECI': eci_norm})
df_eci.sort_values('ECI', ascending=False, inplace=True)
df_eci = df_eci.merge(df_RCA.groupby([location])[['M']].sum().sort_values(by='M', ascending=False).reset_index().rename(columns={location:"location"}),how='left')
df_eci[0:56]

   location       ECI    M
0     16980  3.948570  425
1     31080  3.871481  436
2     41940  3.705058  139
3     14460  3.624921  300
4     17410  3.598159  313
5     35620  3.458689  339
6     37980  3.422491  317
7     41860  3.407008  284
8     17140  3.394944  273
9     12060  3.353760  347
10    19820  3.346232  299
11    33340  3.327017  291
12    19100  3.295671  380
13    33460  3.233839  332
14    26420  3.137808  334
15    16740  3.012000  304
16    42660  2.899158  279
17    34980  2.816913  269
18    38300  2.806183  288
19    33100  2.805399  341
20    38900  2.804901  370
21    41180  2.761540  298
22    41740  2.758916  316
23    40140  2.757561  355
24    28140  2.723622  276
25    24340  2.716684  298
26    47900  2.650087  201
27    18140  2.625360  233
28    38060  2.578343  315
29    39300  2.553978  293
30    31140  2.535880  242
31    40380  2.510758  245
32    25540  2.480082  220
33    21140  2.456030  144
34    41620  2.419226  296
35    10900  2.413174  217
36    45300  2.385246  317
37    19740  2.382047  317
38    12580  2.376374  262
39    26900  2.366060  257
40    15380  2.351362  269
41    36740  2.321951  246
42    32820  2.318790  200
43    24660  2.236479  232
44    29820  2.150147  213
45    14860  2.130002  250
46    12420  2.126972  281
47    20500  2.098762  117
48    24860  2.096348  233
49    49340  2.082618  225
50    31540  2.035816  221
51    10420  1.982175  216
52    19430  1.960146  207
53    39340  1.942666  210
54    14500  1.933595  212
55    35300  1.920110  164

### 4.1 Calculate $\hat{M}$ matrix

In [32]:
temp_Mpa_2 = Mpa.copy().astype(float)
for i in range(len(locations)):
    temp_Mpa_2[i, :] = temp_Mpa_2[i, :]/diversity[i]

In [33]:
Sppprima = np.matmul(Mpa.transpose(), temp_Mpa_2)
Sppprima.shape, Sppprima.dtype

((964, 964), dtype('float64'))

In [34]:
Mmonio_p = np.matmul(U_inv, Sppprima)
Mmonio_p.shape, Mmonio_p.dtype

((964, 964), dtype('float64'))

In [35]:
pci_raw = calc_complexity(Mmonio_p)

In [36]:
if data_choice == "trade":
    df_product_codes=pd.read_excel(DATASETS_DIR + "BACI/HSCodeandDescription.xlsx", sheet_name="HS22")
    df_product_codes = df_product_codes.loc[df_product_codes["Level"]== 6]
elif data_choice == "labor":
    df_product_codes= pd.read_excel(DATASETS_DIR + "2022_NAICS_Descriptions.xlsx")
    df_product_codes["Title"] = df_product_codes["Title"].str.replace("T$", "", regex=True).str.strip()
    df_product_codes['Code'] = df_product_codes['Code'].astype(str) # Ensure NAICS is string*
    df_product_codes = df_product_codes[["Code", "Title"]]
    df_product_codes.rename(columns={"Title":"Description"}, inplace=True)

In [37]:
# Let's check now results on PCI. 
# Also check that the PCIs are not reversed. If they are reversed, run next cell to change their sign. This is because the eigenvector calculation has an indeterminate direction and must be determined manually.
pci_norm = (pci_raw - pci_raw.mean())/pci_raw.std()
pci_norm = pci_norm
print('Mean and std of ICA:', pci_norm.mean(), '+/-', pci_norm.std())

df_pci = pd.DataFrame({code: products, 'PCI': pci_norm}).merge(df_product_codes[["Code", "Description"]].drop_duplicates(subset=["Code", "Description"]), how="left", left_on=code, right_on="Code")
df_pci.sort_values(by="PCI", ascending=False)[0:20]

Mean and std of ICA: -5.896620213776765e-17 +/- 1.0

,NAICS2017,PCI,Code,Description
906,336419,2.547506,336419,Other Guided Missile and Space Vehicle Parts a...
927,332112,2.519511,332112,Nonferrous Forging
933,523210,2.499710,523210,Securities and Commodity Exchanges
905,334613,2.415307,NaN,NaN
935,212393,2.386609,NaN,NaN
958,212299,2.237048,NaN,NaN
932,522293,2.156430,NaN,NaN
798,332913,2.150290,332913,Plumbing Fixture Fitting and Trim Manufacturing
929,336112,2.142556,NaN,NaN
814,335110,2.135145,NaN,NaN
928,333997,2.124268,NaN,NaN
942,812922,2.059221,812922,One-Hour Photofinishing
917,325130,2.036983,325130,Synthetic Dye and Pigment Manufacturing
804,333991,2.032150,333991,Power-Driven Handtool Manufacturing
922,311422,1.996214,311422,Specialty Canning
930,339993,1.971757,339993,"Fastener, Button, Needle, and Pin Manufacturing"
950,562213,1.966392,562213,Solid Waste Combustors and Incinerators
876,483112,1.951079,483112,Deep Sea Passenger Transportation
903,334112,1.941531,334112,Computer Storage Device Manufacturing
754,311930,1.930774,311930,Flavoring Syrup and Concentrate Manufacturing

In [38]:
# Prepare arrays to export

df_RCA = df_RCA.merge(df_pci[[code, "PCI"]], how="left", on = code)

RCA = np.zeros((df_RCA[location].nunique(), df_RCA[code].nunique()),
               dtype=np.float64)

for row in df_RCA.loc[df_RCA.RCA != 0.0].iterrows():
    RCA[row[1].loc_int, row[1].prod_int] = row[1].RCA

value_level = np.zeros((df_RCA[location].nunique(), df_RCA[code].nunique()),
               dtype=np.float64)

# Fill RCA where you have to
for row in df_RCA.iterrows():
    value_level[row[1].loc_int, row[1].prod_int] = row[1][variable]

In [39]:
ENGINE, COMP = "fastparquet", "snappy" 

pd.DataFrame(Mpa, index=list(locations), columns=list(products))\
  .to_parquet(OUTPUTS_DIR + f"Mpa.parquet", engine=ENGINE, compression=COMP)

pd.DataFrame({"codes": list(products)})\
  .to_parquet(OUTPUTS_DIR + f"codes.parquet", engine=ENGINE, compression=COMP, index=False)

pd.DataFrame({"location": list(locations)})\
  .to_parquet(OUTPUTS_DIR + f"locations.parquet", engine=ENGINE, compression=COMP, index=False)

pd.DataFrame(np.asarray(RCA), index=list(locations), columns=list(products))\
  .to_parquet(OUTPUTS_DIR + f"RCA.parquet", engine=ENGINE, compression=COMP)

pd.DataFrame({"eci_norm": list(eci_norm)})\
  .to_parquet(OUTPUTS_DIR + f"eci.parquet", engine=ENGINE, compression=COMP, index=False)

pd.DataFrame({"pci_norm": list(pci_norm)})\
  .to_parquet(OUTPUTS_DIR + f"pci.parquet", engine=ENGINE, compression=COMP, index=False)

pd.DataFrame(value_level, index=list(locations), columns=list(products))\
  .to_parquet(OUTPUTS_DIR + f"value_level.parquet", engine=ENGINE, compression=COMP)

## 5. Proximity
Calculate product proximity: how likely it is for two products to be co-exported.

In [40]:
p_RCAmay1 = np.zeros((len(products),))

for prod in range(len(products)):
    p_RCAmay1[prod] = Mpa[:, prod].sum()

In [41]:
# Calculamos la proximidad: la probabilidad condicional mínima de que una icaa tenga el sector i RCA>1 dado tiene el sector j con RCA>1, y viceversa.
# Miramos entonces primero la cantidad de icas en que ambos sectores tienen RCA, lo sumo y divido por la mayor ubicuidad de ambos sectores.

almost_proximity = np.zeros((len(products), len(products)))

for p1 in range(len(products)-1):
    # como es una matriz simetrica, calcula unicamente la mitad de los valores:
    for p2 in range(p1+1, len(products)):
        almost_proximity[p1, p2] = np.logical_and(Mpa[:, p1], Mpa[:, p2]).sum()/max(p_RCAmay1[p1], p_RCAmay1[p2])

In [42]:
len(products)

964

In [43]:
# chequeo que no haya valores incorrectamente imputados
for i in range(len(products)):
    if not np.isclose(almost_proximity[i, :i].sum(), 0.0):
        print('something wrong at row', i)

In [44]:
proximity = almost_proximity + almost_proximity.transpose() + np.diag(np.ones(len(products)))

In [45]:
proximity.shape

(964, 964)

## 6. Calculate Density

Measures how close a new product is to the set of products a region already exports. Helps assess diversification feasibility.

$$
d_{pa} = \dfrac{\sum_{a'} M_{pa'} \Phi_{a,a'}}{\sum_{a'} \Phi_{a,a'}}
$$

In [46]:
#numerador
density_pa = np.matmul(Mpa, proximity)
print(density_pa.shape)

#denominador
for i in range(len(products)):
    density_pa[:, i] = density_pa[:, i]/proximity[:, i].sum()

(925, 964)

In [47]:
relative_density = np.zeros(density_pa.shape)

for p in range(density_pa.shape[0]):
    mask = Mpa[p] - 1
    # Acá me quedo con todos los productos donde no tengo VCR
    den_option_set = density_pa[p][mask.astype(bool)]  
    relative_density[p] = (density_pa[p] - den_option_set.mean()) / den_option_set.std()

## 7. Calculate Strategic Value (COG)

Strategic Value (COG) estimates the potential benefit of moving into a new product, considering its complexity and distance to current capabilities.

$$COG_{pa} = [\sum_{a'} \dfrac{\phi_{a,a'}}{\sum_{a''} \phi_{a'',a'}}(1 - M_{pa'}) ICA_{a'}] - (1 - d_{pa})ICA_{a}$$

In [48]:
non_RCA_all = np.ones((len(locations), len(products)), dtype=np.int64) - Mpa
non_RCA_all = non_RCA_all.astype(float)

distance_pa = np.matmul(non_RCA_all, proximity)

for i in range(len(products)):
    distance_pa[:, i] = distance_pa[:, i]/proximity[i, :].sum()

inv_distance_pa = np.ones((len(locations), len(products)), float) - distance_pa

In [49]:
ica_U01 = pci_norm - min(pci_norm)
ica_U01 = ica_U01 / max(ica_U01)

In [50]:
unif_A = np.zeros((len(locations), len(products)), float)
unif_B = np.zeros((len(locations), len(products)), float)
sum_prox = proximity.sum(axis = 0)

for l in range(len(locations)):
    if l % 13 == 0:
        print('.', end=' ')
        
    for a in range(len(products)):
        unif_A[l, a] = (proximity[a, :]*non_RCA_all[l, :]*ica_U01/sum_prox).sum()
        unif_B[l, a] = inv_distance_pa[l, a]*ica_U01[a]

unif_cog2_pa = unif_A - unif_B

. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .

In [51]:
relative_cog = np.zeros((len(locations), len(products)), float)
for idx_prov in range(len(locations)):
    relative_cog[idx_prov,] = unif_cog2_pa[idx_prov] - unif_cog2_pa[idx_prov][(1 - Mpa[idx_prov]).astype(bool)].mean()
    relative_cog[idx_prov,] /= unif_cog2_pa[idx_prov][(1 - Mpa[idx_prov]).astype(bool)].std()

In [52]:
pd.DataFrame(proximity, index=list(products), columns=list(products))\
  .to_parquet(OUTPUTS_DIR + f"proximity.parquet", engine=ENGINE, compression=COMP)

pd.DataFrame(relative_density, index=list(locations), columns=list(products))\
  .to_parquet(OUTPUTS_DIR + f"relative_density.parquet", engine=ENGINE, compression=COMP)

pd.DataFrame(relative_cog, index=list(locations), columns=list(products))\
  .to_parquet(OUTPUTS_DIR + f"relative_cog.parquet", engine=ENGINE, compression=COMP)